### ISSUE TITLE
support for disabling the module cache

### ISSUE THREAD

**Issue by jvasileff** [jvasileff/vscode-ceylon#4]
Commit https://github.com/jvasileff/vscode-ceylon/commit/5702b7e8e85d4b8d93c4c424c10dce125b261025 added support for module caching in JS, which, among other things, means that imported modules that are not being compiled (i.e. modules loaded from json) will not refreshed once loaded until Visual Studio Code is restarted.

This could be less than ideal for development work that involves generating and testing json models. One possible solution would be to have an undocumented setting `ceylon.disableModuleCache` to entirely disable caching.

**Comment by jvasileff** [comment]
@lucaswerkmeister this would be primarily to help out with your typescript work. Once you get a feel for VSCode, let me know what you think. Is this necessary? Any other ideas?

**Comment by lucaswerkmeister** [comment]
I don’t know if I need this. For me, it would only be useful for the test module, since the `tsc` module doesn’t change. It sounds like a good idea, but for me it’s not high priority. (And if module caching helps performance, I probably wouldn’t disable the module cache anyways.)

A different idea: perhaps you can watch the filesystem for changes to the JS module files?

**Comment by jvasileff** [comment]
Cool, that makes this easy. I'll close it for now.

RE watching for changes–that adds complexity that I think I'd rather avoid. For files inside the workspace, VSCode handles file watching with all of the appropriate OS hooks.
